/**
 * Absolute Stability Consensus Engine (v4.0)
 */
import { getGoogleTrendsData, buildCompetitorLinks } from './google-trends';
import { extractJSON, withRetry } from './retry';
import { fetchInternetDataViaTool } from './internet-search';
import { RESEARCH_MODELS } from './models';

export async function consensusResearch(query: string, tier: string = 'FREE') {
  const isBasic = tier === 'FREE' || tier === 'STARTER';

  // Limit: 55 seconds (to stay under 60s maxDuration limit)
  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error('TIMEOUT_LIMIT')), 55000)
  );

  const taskPromise = (async () => {
    console.log(`[Consensus] Starting research for: ${query}`);
    
    // 1. Parallel Data Fetch (Strict 1s timeout for Hobby plan)
    const [internetData, trendsData] = await Promise.all([
      Promise.race([
        fetchInternetDataViaTool(query).catch(() => ""), 
        new Promise<string>(r => setTimeout(() => r(""), 1000))
      ]),
      Promise.race([
        getGoogleTrendsData(query).catch(() => null),
        new Promise<null>(r => setTimeout(() => r(null), 1000))
      ])
    ]);

    const context = internetData ? `\n\n--- INTERNET DATA ---\n${internetData}\n\n` : "";

    // 2. AI Analysis with Instant Failover
    let usedModel = "Gemini 2.0 Flash";
    const analysis = await withRetry(async (modelId) => {
      usedModel = modelId || RESEARCH_MODELS.PRIMARY.id;
      const { getCline } = await import('./cline');
      const response = await getCline().chat.completions.create({
        model: usedModel,
        messages: [
          {
            role: 'system',
            content: `You are a professional e-commerce product researcher. Analyze the market for: "${query}". Context: ${context}. Return results in JSON format.`
          },
          {
            role: 'user',
            content: `Provide a detailed product analysis in valid JSON format: {"products": [{"name": "...", "score": 85, "category": "...", "wholesalePrice": "...", "retailPrice": "...", "profitMargin": "...", "competition": "Low|Medium|High", "trend": "Rising|Stable", "description": "...", "whyItWorks": "...", "targetAudience": "...", "marketingTips": [], "sources": []}], "summary": "..."}. Focus on real, trending products.`
          }
        ],
        temperature: 0.7,
        max_tokens: 2000
      });

      const content = response.choices[0]?.message?.content;
      if (!content) throw new Error("Empty AI response");
      
      const extracted = extractJSON(content);
      const parsed = JSON.parse(extracted);
      
      if (!parsed.products || !Array.isArray(parsed.products)) {
        throw new Error("Invalid AI JSON structure");
      }
      
      return parsed;
    });

    // 3. Simple Enrichment
    const products = (analysis.products || []).map((p: any) => ({
      ...p,
      competitorLinks: buildCompetitorLinks(p.name),
      googleTrendsData: trendsData,
      googleTrendsInsight: trendsData?.summary || "Global trend data utilized.",
      agreedByCount: 1
    }));

    return {
      products,
      summary: analysis.summary || "Analysis successfully generated by AllMySell AI.",
      aiProviders: [usedModel],
      consensusMethod: "Consensus-V4 (Stable)"
    };
  })();

  return Promise.race([taskPromise, timeoutPromise]);
}

export async function consensusTrends(niche: string) {
  return withRetry(async (modelId) => {
    const { getCline } = await import('./cline');
    const response = await getCline().chat.completions.create({
      model: modelId!,
      messages: [{ role: 'user', content: `Analyze trends for: ${niche}. Return JSON: {"categories": [...]}` }],
      temperature: 0.9
    });
    const analysis = JSON.parse(extractJSON(response.choices[0]?.message?.content || "{}"));
    return {
      engine: "Gemini Stable",
      niche: niche || 'general',
      trends: { ...analysis, sources: [] }
    };
  });
}
