from fastapi import FastAPI, HTTPException, BackgroundTasks, Depends, Header
from pydantic import BaseModel
from typing import Optional, List
import os
from datetime import datetime
import asyncio
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="AllMySell Automation API", description="API wrapper for Python scraping and automation bots")

# In-memory status tracking for demonstration (In production, use Supabase database)
bot_status = {
    "trend_hunter": {"status": "idle", "last_run": None, "items_processed": 0},
    "ebay_sync": {"status": "idle", "last_run": None, "items_processed": 0}
}

# Simple Auth Dependency
async def verify_token(x_api_key: str = Header(...)):
    # In production, verify this token matches the one generated by your Next.js backend
    # or verify user's JWT with Supabase Admin SDK
    expected_token = os.getenv("API_SECRET_KEY", "dev_secret_key")
    if x_api_key != expected_token:
        raise HTTPException(status_code=401, detail="Unauthorized")
    return True

class BotLaunchRequest(BaseModel):
    niche: Optional[str] = None
    target_platform: Optional[str] = None

# Mock functions for your actual bot scripts
async def run_trend_hunter_bot(niche: Optional[str]):
    bot_status["trend_hunter"]["status"] = "running"
    print(f"Starting Trend Hunter Bot for niche: {niche or 'general'}")
    
    # Simulate bot execution time
    for i in range(1, 11):
        await asyncio.sleep(2)
        bot_status["trend_hunter"]["items_processed"] = i * 10
        print(f"Trend Hunter scraping... {i*10}% done")
        
    bot_status["trend_hunter"]["status"] = "idle"
    bot_status["trend_hunter"]["last_run"] = datetime.now().isoformat()
    # Here you would typically save results to Supabase

async def run_ebay_sync_bot():
    bot_status["ebay_sync"]["status"] = "running"
    print("Starting eBay Sync Bot...")
    
    # Simulate execution
    await asyncio.sleep(10)
    
    bot_status["ebay_sync"]["status"] = "idle"
    bot_status["ebay_sync"]["last_run"] = datetime.now().isoformat()

@app.get("/")
def read_root():
    return {"status": "online", "message": "AllMySell Automation Engine API"}

@app.get("/api/bots/status", dependencies=[Depends(verify_token)])
def get_status():
    """Get the current running status of all bots"""
    return bot_status

@app.post("/api/bots/trend-hunter/start", dependencies=[Depends(verify_token)])
def start_trend_hunter(bg_tasks: BackgroundTasks, request: BotLaunchRequest):
    """Launch the Trend Hunter scraping bot"""
    if bot_status["trend_hunter"]["status"] == "running":
        raise HTTPException(status_code=400, detail="Bot is already running")
        
    bg_tasks.add_task(run_trend_hunter_bot, request.niche)
    return {"message": "Trend Hunter bot started successfully", "status": "running"}

@app.post("/api/bots/ebay-sync/start", dependencies=[Depends(verify_token)])
def start_ebay_sync(bg_tasks: BackgroundTasks):
    """Launch the eBay Synchronization bot"""
    if bot_status["ebay_sync"]["status"] == "running":
        raise HTTPException(status_code=400, detail="Bot is already running")
        
    bg_tasks.add_task(run_ebay_sync_bot)
    return {"message": "eBay Sync bot started successfully", "status": "running"}

@app.post("/api/bots/{bot_id}/stop", dependencies=[Depends(verify_token)])
def stop_bot(bot_id: str):
    """Stop a running bot (pseudo-implementation)"""
    if bot_id not in bot_status:
        raise HTTPException(status_code=404, detail="Bot not found")
        
    # Real implementation would require process killing or thread signaling
    bot_status[bot_id]["status"] = "idle"
    return {"message": f"{bot_id} bot stopped gracefully"}
