import { NextResponse } from 'next/server';
import { NicheDiscoverer } from '@/lib/ai/niche-discoverer';

export async function POST(req: Request) {
  try {
    const { strategy } = await req.json();
    console.log(`[Discovery API] Strategy received: ${strategy}`);
    
    const discoverer = new NicheDiscoverer();
    const niches = await discoverer.discover(strategy || 'mashup');

    if (!niches || niches.length === 0) {
      console.warn("[Discovery API] No niches generated by AI");
      return NextResponse.json({ success: false, error: "AI failed to generate ideas" }, { status: 500 });
    }

    console.log(`[Discovery API] Successfully generated ${niches.length} niches`);
    return NextResponse.json({
      success: true,
      niches
    });

  } catch (error: any) {
    console.error("[Discovery API] CRITICAL ERROR:", error);
    return NextResponse.json({ 
      success: false, 
      error: error.message || "Internal Discovery Error" 
    }, { status: 500 });
  }
}
